In [27]:
from sklearn.datasets import load_iris      # or load_wine

In [28]:
import pandas as pd

In [29]:
iris = load_iris()                          # loads toy dataset [web:16][web:19]

In [30]:

X = iris.data   # features

In [31]:
y = iris.target # target labels

In [32]:
df2 = pd.DataFrame(X, columns=iris.feature_names)

In [33]:
df2["target"] = y

In [34]:
print(df2.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target
0       0
1       0
2       0
3       0
4       0

In [35]:
df2.shape

(150, 5)

In [36]:
type(df2)

pandas.core.frame.DataFrame

In [37]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [38]:
# shows how many missing (null/NaN) values are in each column.
df2.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [39]:
df2.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [41]:
print(df2.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [42]:
df2['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [43]:
df2['petal length (cm)'].value_counts(normalize=True)

petal length (cm)
1.4    0.086667
1.5    0.086667
4.5    0.053333
5.1    0.053333
1.3    0.046667
1.6    0.046667
5.6    0.040000
4.9    0.033333
4.0    0.033333
4.7    0.033333
1.7    0.026667
4.8    0.026667
5.0    0.026667
4.4    0.026667
4.2    0.026667
4.1    0.020000
3.9    0.020000
5.8    0.020000
5.7    0.020000
5.5    0.020000
6.1    0.020000
4.6    0.020000
1.9    0.013333
5.2    0.013333
5.4    0.013333
1.2    0.013333
3.3    0.013333
3.5    0.013333
6.7    0.013333
5.3    0.013333
4.3    0.013333
5.9    0.013333
6.0    0.013333
1.0    0.006667
1.1    0.006667
3.7    0.006667
3.8    0.006667
3.6    0.006667
3.0    0.006667
6.3    0.006667
6.6    0.006667
6.9    0.006667
6.4    0.006667
Name: proportion, dtype: float64

In [ ]:
df2.isnull().sum()

In [44]:
df2.corr(numeric_only=True)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
sepal length (cm),1.000000,-0.117570,0.871754,0.817941,0.782561
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126,-0.426658
petal length (cm),0.871754,-0.428440,1.000000,0.962865,0.949035
petal width (cm),0.817941,-0.366126,0.962865,1.000000,0.956547
target,0.782561,-0.426658,0.949035,0.956547,1.000000

In [ ]:
df2.groupby('species').mean(numeric_only=True)

In [ ]:
df2[df2['sepal length'] > 5.0]

In [ ]:
df2.select_dtypes(include='number').head()

In [46]:
df2.sort_values('sepal length (cm)')

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
13,4.3,3.0,1.1,0.1,0
8,4.4,2.9,1.4,0.2,0
42,4.4,3.2,1.3,0.2,0
38,4.4,3.0,1.3,0.2,0
41,4.5,2.3,1.3,0.3,0
...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,2
117,7.7,3.8,6.7,2.2,2
118,7.7,2.6,6.9,2.3,2
135,7.7,3.0,6.1,2.3,2
131,7.9,3.8,6.4,2.0,2

In [ ]:
df2.nunique()

In [ ]:
df2.rename(columns={'sepal length (cm)': 'sepal_length'}, inplace=False)

In [ ]:
df2['sepal length (cm)'].mean()

In [48]:
df2['sepal_area'] = df2['sepal length (cm)'] * df2['sepal width (cm)']